### ISSUE TITLE
admin password

### ISSUE THREAD

**Issue by nnsense** [solidyn/docker#3]
Hi,
I know that the dockerfile has no setting about the admin password so this issue is totally unrelated your image but I really cannot figure out what's the web admin password, I've tried changeme as stated on the ec2box github page but it doesn't work, any help would be appreciated.

Thanks!

**Comment by aztechian** [comment]
Hi,
yes, it appears I broke that by making the db location a volume. Apologies.
I'll probably just revert the `VOLUME` line in the dockerfile, until I can get it fully figured out.
Without specifying a database volume to `docker run`, the process doesn't have write permissions to that folder any longer.

**Comment by nnsense** [comment]
I see :)  So meanwhile I could rebuild it myself removing the "volume" line from your dockerfile. Got it, thank you :)

**Comment by nnsense** [comment]
Yes! Works great, thank you 👍

**Comment by aztechian** [comment]
@nnsense this has been updated on docker hub now. tag `0.35.00` -> `latest`.
Thanks for letting me know.
